INSERT INTO tool_type (type) values ('Software');INSERT INTO tool (description,name,type,manufacturer) VALUES ('The SeaWiFS Data Analysis System (SeaDAS) is a comprehensive image analysis package for the processing, display, analysis, and quality control of ocean color data.','Seadas',(SELECT id FROM tool_type WHERE type='Software'),'NASA OBBPG');
INSERT INTO tool_type (type) values ('Sensor');INSERT INTO tool (name,type) VALUES ('Rain Gauge HIRS',(SELECT id FROM tool_type WHERE type='Sensor'));
INSERT INTO tool (description,name,type,manufacturer) VALUES ('Data recorded: Sea Temperature (2.4m and 7.2m at MSL), Barometric Pressure, Air Temperature, Solar Radiation (PAR), Wind Direction True (scalar averaged), Wind Speed True (10 min average prior to every half hour and maximum wind gust). The weather station uses Campbell Scientific Australia equipment.','HALFTIDE ROCKS RWS AIMS',(SELECT id FROM tool_type WHERE type='Sensor'),'AIMS');
INSERT INTO tool (name,type) VALUES ('Wet Dry Bulb HIRS',(SELECT id FROM tool_type WHERE type='Sensor'));
INSERT INTO tool (name,type) VALUES ('Barometer HIRS',(SELECT id FROM tool_type WHERE type='Sensor'));
INSERT INTO tool (name,type) VALUES ('Anemometer HIRS',(SELECT id FROM tool_type WHERE type='Sensor'));
INSERT INTO tool (description,name,type,manufacturer) VALUES ('Data recorded: Sea Temperature (2.5m and 9m at MSL), Barometric Pressure, Air Temperature, Solar Radiation (PAR), Wind Direction True (vector averaged), Wind Speed True (30 min average). This weather station has been deployed in three different locations on Hardy Reef.&#xD; Location 1: -19.7340S, 149.1808E  from June 1989 to November 1993 Location 2: -19.7358S, 149.1808E from November 1993 to January 1996 Location 3: -19.7473S, 149.1817E from January 1996 to present. The weather station is an AIMS System','HARDY REEF RWS AIMS',(SELECT id FROM tool_type WHERE type='Sensor'),'AIMS');
INSERT INTO tool (name,type) VALUES ('Tide Gauge HIRS',(SELECT id FROM tool_type WHERE type='Sensor'));
INSERT INTO tool (name,type) VALUES ('Mercury Thermometer HIRS',(SELECT id FROM tool_type WHERE type='Sensor'));
INSERT INTO tool (description,model_number,name,type,manufacturer) VALUES ('WATERPROOF RECORDER The Odyssey data recorder is waterproof and submersible to 20 metres.  TEMPERATURE RESOLUTION Temperature range is between -10 degrees centigrade and +50 degrees centigrade. The temperature resolution is 0.02 degrees centigrade.  TEMPERATURE READINGS The Odyssey data recorder records 16350 temperature readings. The interval between readings can be set when the recorder is started at any interval between 10 seconds (8640 readings per day) and 8 hours (3 readings per day).  SIZE The physical size of this system (data recorder and temperature sensor) is 39mm diameter and 160mm long.  BATTERIES The Odyssey data recorder includes two ½ AA Lithium cells spot welded together. The batteries can be purchased from Dataflow Systems.  APPLICATIONS      Water, Soil & Air  SOFTWARE Windows version PC software Odyssey V4.6 Microsoft English and V4.4 Microsoft Chinese. http://www.odysseydatarecording.com/odyssey_productsview.php?key=7','ODYTEMP','Odyssey Temperature Logger AIMS',(SELECT id FROM tool_type WHERE type='Sensor'),'DATAFLOW Systems Pty Ltd.');
INSERT INTO tool (description,name,type,manufacturer) VALUES ('Data recorded: Barometric Pressure, Air Temperature, Solar Radiation (PAR), Wind Direction True (vector averaged), Wind Speed True (30 min average). The weather station is an AIMS System.','CAPE BOWLING GREEN RWS AIMS',(SELECT id FROM tool_type WHERE type='Sensor'),'AIMS');
INSERT INTO tool (name,type) VALUES ('MODIS',(SELECT id FROM tool_type WHERE type='Sensor'));
INSERT INTO tool (name,type) VALUES ('Thermometer',(SELECT id FROM tool_type WHERE type='Sensor'));
INSERT INTO tool_type (type) values ('Quadrat');INSERT INTO tool (name,type) VALUES ('Quadrat',(SELECT id FROM tool_type WHERE type='Quadrat'));
INSERT INTO characteristic (name,description) VALUES ('Count','Count');
INSERT INTO characteristic (name,description) VALUES ('Temperature','Temperature');
INSERT INTO characteristic (name,description) VALUES ('Air_Temperature','Air Temperature');
INSERT INTO characteristic (name,description) VALUES ('Sea_Surface_Temperature','Sea Surface Temperature');
INSERT INTO characteristic (name,description) VALUES ('Sea_Water_Temperature','Sea Water Temperature');
INSERT INTO characteristic (name,description) VALUES ('Length','Length');
INSERT INTO characteristic (name,description) VALUES ('Height','Height');
INSERT INTO characteristic (name,description) VALUES ('Tide','Tide');
INSERT INTO characteristic (name,description) VALUES ('Depth','Depth');
INSERT INTO characteristic (name,description) VALUES ('Zeu','Zeu');
INSERT INTO characteristic (name,description) VALUES ('Amount','Amount');
INSERT INTO characteristic (name,description) VALUES ('Rain_Fall','Rain Fall');
INSERT INTO characteristic (name,description) VALUES ('Direction','Direction');
INSERT INTO characteristic (name,description) VALUES ('Wind_Direction','Wind Direction');
INSERT INTO characteristic (name,description) VALUES ('Growth','Growth');
INSERT INTO characteristic (name,description) VALUES ('Hue','Hue');
INSERT INTO characteristic (name,description) VALUES ('Mass','Mass');
INSERT INTO characteristic (name,description) VALUES ('Weight','Weight');
INSERT INTO characteristic (name,description) VALUES ('Speed','Speed');
INSERT INTO characteristic (name,description) VALUES ('Wind_Speed','Wind Speed');
INSERT INTO characteristic (name,description) VALUES ('Concentration','Concentration');
INSERT INTO characteristic (name,description) VALUES ('Bleaching_Level','Bleaching Level');
INSERT INTO characteristic (name,description) VALUES ('Brightness','Brightness');
INSERT INTO characteristic (name,description) VALUES ('Intensity','Intensity');
INSERT INTO characteristic (name,description) VALUES ('ph','ph');
INSERT INTO characteristic (name,description) VALUES ('Humidity','Humidity');
INSERT INTO characteristic (name,description) VALUES ('Air_Humidity','Air Humidity');
INSERT INTO characteristic (name,description) VALUES ('Visibility','Visibility');
INSERT INTO characteristic (name,description) VALUES ('Air_Visibility','Air Visibility');
INSERT INTO characteristic (name,description) VALUES ('Saturation','Saturation');
INSERT INTO characteristic (name,description) VALUES ('Par','Par');
INSERT INTO characteristic (name,description) VALUES ('Turbidity','Turbidity');
INSERT INTO characteristic (name,description) VALUES ('Salinity','Salinity');
INSERT INTO characteristic (name,description) VALUES ('Density','Density');
INSERT INTO characteristic (name,description) VALUES ('Population_Density','Population Density');
INSERT INTO characteristic (name,description) VALUES ('Chlor_a','Chlor a');
INSERT INTO characteristic (name,description) VALUES ('Pressure','Pressure');
INSERT INTO characteristic (name,description) VALUES ('Air_Pressure','Air Pressure');
INSERT INTO characteristic (name,description) VALUES ('Derived_Characteristic','Derived Characteristic');
INSERT INTO characteristic (name,description) VALUES ('Volume','Volume');
INSERT INTO characteristic (name,description) VALUES ('Area','Area');
INSERT INTO characteristic (name,description) VALUES ('Area_Per_Quadrat','Area Per Quadrat');
INSERT INTO unit (description,name) VALUES ('h','hour');
INSERT INTO unit (description,name) VALUES ('ml','ml');
INSERT INTO unit (description,name) VALUES ('AIMS Bleaching Level','AIMS_Bleaching_Level');
INSERT INTO unit (description,name) VALUES ('°C','Degrees_Celcius');
INSERT INTO unit (description,name) VALUES ('m','m');
INSERT INTO unit (description,name) VALUES ('cm','cm');
INSERT INTO unit (description,name) VALUES ('Colour','Colour');
INSERT INTO unit (description,name) VALUES ('Coral Watch Hue','Coral_Watch_Hue');
INSERT INTO unit (description,name) VALUES ('°','Degree');
INSERT INTO unit (description,name) VALUES ('km','km');
INSERT INTO unit (description,name) VALUES ('mg','mg');
INSERT INTO unit (description,name) VALUES ('uEm-2s-1','uEm-2s-1');
INSERT INTO unit (description,name) VALUES ('kn','Knots');
INSERT INTO unit (description,name) VALUES ('mg / m³','mg_per_m3');
INSERT INTO unit (description,name) VALUES ('%','Percent');
INSERT INTO unit (description,name) VALUES ('hPa','hPa');
INSERT INTO unit (description,name) VALUES ('kmh','kmh');
INSERT INTO unit (description,name) VALUES ('Coral Watch Intensity','Coral_Watch_Intensity');
INSERT INTO unit (description,name) VALUES ('pH','pH');
INSERT INTO unit (description,name) VALUES ('km²','km2');
INSERT INTO unit (description,name) VALUES ('m²','m2');
INSERT INTO unit (description,name) VALUES ('cm²','cm2');
INSERT INTO actor_type (type) VALUES ('Person');
INSERT INTO actor (name,email,type) VALUES ('CMS Bleaching Survey Team','',(SELECT id FROM actor_type WHERE type='Person'));
INSERT INTO actor (name,email,type) VALUES ('Ray Berkelmans','r.berkelmans@aims.gov.au',(SELECT id FROM actor_type WHERE type='Person'));
INSERT INTO actor (name,email,type) VALUES ('Juan Carlos Ortiz','j.ortiz@uq.edu.au',(SELECT id FROM actor_type WHERE type='Person'));
INSERT INTO actor (name,email,type) VALUES ('Guillermo Diaz','g.diazpulido@uq.edu.au',(SELECT id FROM actor_type WHERE type='Person'));
INSERT INTO actor (name,email,type) VALUES ('HIRS Staff','hirs@uq.edu.au',(SELECT id FROM actor_type WHERE type='Person'));
INSERT INTO actor (name,email,type) VALUES ('Scarla Weeks','s.weeks@uq.edu.au',(SELECT id FROM actor_type WHERE type='Person'));
INSERT INTO actor_type (type) VALUES ('Process');
INSERT INTO actor_type (type) VALUES ('Machine');
INSERT INTO actor (name,type) VALUES ('BOM Weather Station',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Thermometer',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Tide Gauge HIRS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Rain Gauge HIRS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Mercury Thermometer HIRS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Barometer HIRS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Wet Dry Bulb HIRS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Anemometer HIRS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('MODIS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('HALFTIDE ROCKS RWS AIMS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('CAPE BOWLING GREEN RWS AIMS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('HARDY REEF RWS AIMS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Odyssey Temperature Logger AIMS',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO actor (name,type) VALUES ('Seadas',(SELECT id FROM actor_type WHERE type='Machine'));
INSERT INTO program (name) VALUES ('CMS_Coral_Bleaching_Research');
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'CMS_Coral_Bleaching_Research'),(SELECT id from actor where name = 'CMS Bleaching Survey Team'));
INSERT INTO program (name) VALUES ('AIMS_Coral_Bleaching_Research');
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'AIMS_Coral_Bleaching_Research'),(SELECT id from actor where name = 'Ray Berkelmans'));
INSERT INTO program (methodology,url,name) VALUES ('Follows a set  transects at the site and samples coral colong size and growth rates over time','www.cms.uq.edu.au','CMS_Coral_Research');
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'CMS_Coral_Research'),(SELECT id from actor where name = 'Juan Carlos Ortiz'));
INSERT INTO program (methodology,url,name) VALUES ('Follows a random transect at the site and samples algae and substrate','www.cms.uq.edu.au','CMS_Algae_Research');
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'CMS_Algae_Research'),(SELECT id from actor where name = 'Guillermo Diaz'));
INSERT INTO program (methodology,url,name) VALUES ('HIRS Staff check on sea temperature, tide and air visibility at 9am each morning.','www.marine.uq.edu.au/hirs','HIRS_Station');
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'HIRS_Station'),(SELECT id from actor where name = 'Tide Gauge HIRS'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'HIRS_Station'),(SELECT id from actor where name = 'HIRS Staff'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'HIRS_Station'),(SELECT id from actor where name = 'Rain Gauge HIRS'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'HIRS_Station'),(SELECT id from actor where name = 'Mercury Thermometer HIRS'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'HIRS_Station'),(SELECT id from actor where name = 'Barometer HIRS'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'HIRS_Station'),(SELECT id from actor where name = 'Wet Dry Bulb HIRS'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'HIRS_Station'),(SELECT id from actor where name = 'Anemometer HIRS'));
INSERT INTO program (url,name) VALUES ('www.cms.uq.edu.au','CMS_Satellite_Research');
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'CMS_Satellite_Research'),(SELECT id from actor where name = 'Scarla Weeks'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'CMS_Satellite_Research'),(SELECT id from actor where name = 'Seadas'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'CMS_Satellite_Research'),(SELECT id from actor where name = 'MODIS'));
INSERT INTO program (methodology,url,name) VALUES ('BOM weather station uses various instruments to measure, Air Temp, Wind Direction & Speed, Humidity, Pressure and Rainfall.','www.bom.gov.au','BOM_Weather_Research');
INSERT INTO program (methodology,url,name) VALUES ('In Situ water temperature logger and remote weather station data is recorded every half hour.','www.aims.gov.au','AIMS_Research');
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'AIMS_Research'),(SELECT id from actor where name = 'HALFTIDE ROCKS RWS AIMS'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'AIMS_Research'),(SELECT id from actor where name = 'CAPE BOWLING GREEN RWS AIMS'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'AIMS_Research'),(SELECT id from actor where name = 'HARDY REEF RWS AIMS'));
INSERT INTO program_actor (programID,actorID) VALUES ((SELECT id from program where name = 'AIMS_Research'),(SELECT id from actor where name = 'Odyssey Temperature Logger AIMS'));
INSERT INTO program (methodology,url,name) VALUES ('The colour charts are based on the actual colours of bleached and healthy corals. Each colour square corresponds to a concentration of symbionts contained in the coral tissue. The concentration of symbionts is directly linked to the health of the coral. All you have to do is match the colour of the coral with one of the colours in the coral health monitoring chart. You then record the matching colour codes, along with coral type (species if possible), on the website data sheet (www.coralwatch.org).','www.coralwatch.org','Coral_Watch');
INSERT INTO data_qualifier (qualifier) VALUES ('Day_and_Night');
INSERT INTO data_qualifier (qualifier) VALUES ('Mean');
INSERT INTO data_qualifier (qualifier) VALUES ('Night');
INSERT INTO data_qualifier (qualifier) VALUES ('Day');
INSERT INTO data_qualifier (qualifier) VALUES ('Dead_Coral');
INSERT INTO data_qualifier (qualifier) VALUES ('Minimum');
INSERT INTO data_qualifier (qualifier) VALUES ('Light');
INSERT INTO data_qualifier (qualifier) VALUES ('Bleached_Coral');
INSERT INTO data_qualifier (qualifier) VALUES ('Bleached_Reef');
INSERT INTO data_qualifier (qualifier) VALUES ('Maximum');
INSERT INTO data_qualifier (qualifier) VALUES ('Dark');
INSERT INTO target (description,name) VALUES ('Environment','Environment');
INSERT INTO target (description,name) VALUES ('Air','Air');
INSERT INTO target (description,name) VALUES ('Air Temperature','Air_Temperature');
INSERT INTO target (description,name) VALUES ('Wind Direction','Wind_Direction');
INSERT INTO target (description,name) VALUES ('Wind Speed','Wind_Speed');
INSERT INTO target (description,name) VALUES ('Air Humidity','Air_Humidity');
INSERT INTO target (description,name) VALUES ('Air Pressure','Air_Pressure');
INSERT INTO target (description,name) VALUES ('Air Visibility','Air_Visibility');
INSERT INTO target (description,name) VALUES ('Bare Substrate','Bare_Substrate');
INSERT INTO target (description,name) VALUES ('Rain','Rain');
INSERT INTO target (description,name) VALUES ('Rain Fall','Rain_Fall');
INSERT INTO target (description,name) VALUES ('Sea Water','Sea_Water');
INSERT INTO target (description,name) VALUES ('Tide','Tide');
INSERT INTO target (description,name) VALUES ('Sea Surface Temperature','Sea_Surface_Temperature');
INSERT INTO target (description,name) VALUES ('Sea Water Temperature','Sea_Water_Temperature');
INSERT INTO target (description,name) VALUES ('Par','Par');
INSERT INTO target (description,name) VALUES ('Zeu','Zeu');
INSERT INTO target (description,name) VALUES ('Sand','Sand');
INSERT INTO target (description,name) VALUES ('Chlor_a','Chlor_a');
INSERT INTO target (description,name) VALUES ('Algae','Algae');
INSERT INTO target (description,name) VALUES ('Coral','Coral');
INSERT INTO target (description,name) VALUES ('Bleached Coral','Bleached_Coral');
INSERT INTO target (description,name) VALUES ('Soft Coral','Soft_Coral');
INSERT INTO target (description,name) VALUES ('Dead Coral','Dead_Coral');
INSERT INTO target (description,name) VALUES ('Coral Recruit','Coral_Recruit');
INSERT INTO target (description,name) VALUES ('Sponge','Sponge');
INSERT INTO target (description,name) VALUES ('Bleached Reef','Bleached_Reef');
